export const collection = [
  {
    id: 1,
    img: `https://muzikercdn.com/uploads/product_gallery/1841/184130/main_2e41710a.jpg`,
    title: `Fender Player Series Stratocaster HSS`,
    guitar: true,
    amp: false,
  },

  {
    id: 2,
    img: `https://muzikercdn.com/uploads/product_gallery/2106/210632/main_032f2a75.jpg`,
    title: `Fender American Performer Telecaster`,
    guitar: true,
    amp: false,
  },
  {
    id: 3,
    img: `https://static.keymusic.com/products/128050/XL/gibson-les-paul-studio-50s-tribute-worn-gold-top-4.jpg`,
    title: `Gibson Les Paul Standard GT`,
    guitar: true,
    amp: false,
  },
  {
    id: 4,
    img: `https://cdn.mos.cms.futurecdn.net/ViYzG53dLD4fQsJLEbKKPd-970-80.jpg.webp`,
    title: `PRS SE Custom 24`,
    guitar: true,
    amp: false,
  },
  {
    id: 5,
    img: `https://images.reverb.com/image/upload/s--r-kRrJ8k--/a_90/f_auto,t_large/v1603215334/w7zhgknfkzebytigraqp.jpg`,
    title: `Epiphone Les Paul Modern Sparkling Burgandy`,
    guitar: true,
    amp: false,
  },
  {
    id: 6,
    img: `https://muzikercdn.com/uploads/product_gallery/1719/171950/thumb_d_gallery_base_3ddeb265.jpg`,
    title: `Fender Squier Bullet Stratocaster`,
    guitar: true,
    amp: false,
  },
  {
    id: 7,
    img: `https://muzikercdn.com/uploads/products/3338/333853/main_322dea16.jpg`,
    title: `Vox Pathfinder 10`,
    guitar: false,
    amp: true,
  },
  {
    id: 8,
    img: `https://muzikercdn.com/uploads/product_gallery/988/98854/main_ab1f01c8.jpg`,
    title: `Fender 65 Twin Reverb`,
    guitar: false,
    amp: true,
  },
  {
    id: 9,
    img: `https://muzikercdn.com/uploads/products/81/8127/main_9bf67f27.jpg`,
    title: `Vox AC30VR Valve Reactor`,
    guitar: false,
    amp: true,
  },
];
