export const projectsData = [
  {
    id: 1,
    title: 'Guitar Practice Assistant',
    img: '/img/practice-assistant.png',
    tags: ['Typescript', 'React', 'Sass', 'Redux', 'MongoDB', 'NodeJs', 'ExpressJS', 'API'],
    codeUrl: 'https://github.com/VWRoli/guitar-practice-assistant',
    liveUrl: 'https://guitar-pa.netlify.app',
    desc: [
      'Guitar practice assistant app, with a built in metronome.',
      'The app is build in Typescript with MERN stack, and using RESTful API design.',
      'I used Redux for state management, Node & Express for API, MongoDB as database.',
      '***Credentials: (username: demoUser1 password: 123456Aa!)',
    ],
  },
  {
    id: 2,
    title: 'Guitar Store',
    img: '/img/guitar-store.png',
    tags: ['React', 'Redux', 'Sass', 'API'],
    codeUrl: 'https://github.com/VWRoli/guitar-store',
    liveUrl: 'https://guitar-store-site.netlify.app/',
    desc: [
      'Complete frontend for a Guitar E-Commerce website with a compare and cart section.',
      'Products are paginated and can be filtered, sorted, searched.',
      'Used JSON Server for creating the Rest API for storing product data',
      'Build with React, Sass, React Router, Redux and different React Hooks',
    ],
  },
  {
    id: 3,
    title: 'Crypto Portfolio Tracker',
    img: '/img/cryptofolio.png',
    tags: ['React', 'Redux', 'Sass', 'API'],
    codeUrl: 'https://github.com/VWRoli/Redux-cryptofolio',
    liveUrl: 'https://cryptofolio-app.netlify.app/',
    desc: [
      'Crypto currency portfolio tracker application. Select or search the currencies you want to add to your portfolio.',
      'Track your assets value. Take a look at the price change chart.',
      'Build with React, state management with Redux. For styling I used Sass.',
      'For getting the currency information I worked with the CoinGecko API.',
    ],
  },

  {
    id: 4,
    title: 'Memory Card Game',
    img: '/img/memory-card-game.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    codeUrl: 'https://codepen.io/VWRoli/pen/MWjqVpg',
    liveUrl: 'https://codepen.io/VWRoli/pen/MWjqVpg',
    desc: [' Memory card game. Created with only Vanilla JS.'],
  },
  {
    id: 5,
    title: 'Crypto Website',
    img: '/img/crypto.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'API', 'SEO'],
    codeUrl: 'https://github.com/VWRoli/kriptosuli',
    liveUrl: 'https://kriptosuli-eu.netlify.app/',
    desc: [
      'Cryptocurrency educational website.',
      'Live cryptocurrency tracker using the Coingecko API.',
      'Fully Responsive Website.',
      'Night mode settings, which are saved with LocalStorage.',
    ],
  },
];
