export const projectsData = [
  {
    id: 1,
    title: 'Crypto Portfolio Tracker',
    img: '/img/cryptofolio.png',
    tags: ['React', 'Sass', 'API'],
    codeUrl: 'https://github.com/VWRoli/React-projects/tree/main/cryptofolio',
    liveUrl: 'https://cryptofolio-app.netlify.app/',
    desc: [
      'Crypto currency portfolio tracker application. Select or search the currencies you want to add to your portfolio.',
      'Track your assets value. Take a look at the price change chart.',
      'Build with React. Using useEffect, useReducer, UseCallback, useContext, React Router.',
      'For getting the currency information I worked with the CoinGecko API, for styling I used Sass.',
    ],
  },
  {
    id: 2,
    title: 'Guitar Practice Assistant',
    img: '/img/practice-assistant.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'OOP', 'Parcel'],
    codeUrl: 'https://github.com/VWRoli/guitar-practice-assistant',
    liveUrl: 'https://guitar-practice-assistant.netlify.app',
    desc: [
      'Guitar practice assistant app, with a built in metronome, and fretboard memorizer.',
      'You can add new excercises on the left side, which will be saved for your next visit.',
      'For creating the metronome I used the Tone JS library which is built on top of the Web Audio API.',
      'The fretboard memorizer is a simple guessing game built with Vanilla JS.',
    ],
  },
  {
    id: 3,
    title: 'Countries',
    img: '/img/countries.png',
    tags: ['CSS', 'React', 'API'],
    codeUrl: 'https://github.com/VWRoli/React-projects/tree/main/countries',
    liveUrl: 'https://countries-2b0dc2.netlify.app/',
    desc: [
      'App that lists all the countries and shows some data about them.',
      'The list is paginated and searchable, and can be filtered by regions.',
      'I used the REST Countries API to get the countries data.',
      'For displaying the countries on the map I used the Leaflet library, with the help of React Leaflet.',
    ],
  },

  {
    id: 4,
    title: 'Memory Card Game',
    img: '/img/memory-card-game.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    codeUrl: 'https://codepen.io/VWRoli/pen/MWjqVpg',
    liveUrl: 'https://codepen.io/VWRoli/pen/MWjqVpg',
    desc: [' Memory card game. Created with only Vanilla JS.'],
  },
  {
    id: 5,
    title: 'Crypto Website',
    img: '/img/crypto.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'API', 'SEO'],
    codeUrl: 'https://github.com/VWRoli/kriptosuli',
    liveUrl: 'https://kriptosuli-eu.netlify.app/',
    desc: [
      'Cryptocurrency educational website.',
      'Live cryptocurrency tracker using the Coingecko API.',
      'Fully Responsive Website.',
      'Night mode settings, which are saved with LocalStorage.',
    ],
  },
];
